<?php
    //FCL= Fake Car List
    $FCL=[
        ["name" => "Toyota","model" => "Corolla","production_year" => 2014,"mileage" => 187000,"price" => 8300,"image"=>"./includes/images/dumdum.jpg","description"=>"Toyota Corolla — Reliable and fuel-efficient compact sedan, perfect for daily commuting, with ample space and modest running costs."],
        ["name" => "Honda","model" => "Civic","production_year" => 2018,"mileage" => 92000,"price" => 5400,"image"=>"./includes/images/dumdum.jpg","description"=>"Honda Civic — Stylish and modern compact car, offering good performance, comfort, and low maintenance for everyday driving."],
        ["name" => "Ford","model" => "F-150","production_year" => 2012,"mileage" => 245000,"price" => 9900,"image"=>"./includes/images/dumdum.jpg","description"=>"Ford F-150 — Robust full-size pickup truck, ideal for heavy loads or towing, combining power, space, and rugged utility."],
        ["name" => "Volkswagen","model" => "Golf","production_year" => 2016,"mileage" => 134000,"price" => 6700,"image"=>"./includes/images/dumdum.jpg","description"=>"Volkswagen Golf — Versatile hatchback with European finesse, compact handling, and comfortable ride — great for city and highway driving."],
        ["name" => "BMW","model" => "320i","production_year" => 2015,"mileage" => 221000,"price" => 9600,"image"=>"./includes/images/dumdum.jpg","description"=>"BMW 320i — Premium midsize sedan with refined handling and smooth engine performance, ideal for those valuing comfort and prestige."],
        ["name" => "Mercedes-Benz","model" => "C200","production_year" => 2017,"mileage" => 158000,"price" => 8800,"image"=>"./includes/images/dumdum.jpg","description"=>"Mercedes-Benz C200 — Sophisticated luxury sedan blending comfort, elegance, and dependable performance — a classy daily driver."],
        ["name" => "Audi","model" => "A4","production_year" => 2013,"mileage" => 276000,"price" => 7950,"image"=>"./includes/images/dumdum.jpg","description"=>"Audi A4 — Well-balanced compact executive car offering a refined interior, smooth drive, and reliable performance for daily or long trips."],
        ["name" => "Nissan","model" => "Altima","production_year" => 2019,"mileage" => 81000,"price" => 6850,"image"=>"./includes/images/dumdum.jpg","description"=>"Nissan Altima — Spacious and comfortable midsize sedan, delivering smooth driving and good fuel efficiency — ideal for families or daily commuters."],
        ["name" => "Hyundai","model" => "Tucson","production_year" => 2011,"mileage" => 309000,"price" => 9400,"image"=>"./includes/images/dumdum.jpg","description"=>"Hyundai Tucson — Practical and compact SUV offering roomy interior, decent fuel economy, and versatile use in city or countryside."],
        ["name" => "Jeep","model" => "Grand Cherokee","production_year" => 2014,"mileage" => 198000,"price" => 7200,"image"=>"./includes/images/dumdum.jpg","description"=>"Jeep Grand Cherokee — Rugged SUV with bold styling and strong performance, built for both city roads and off-road adventures."]];
//-----BELANGRIJK-----!--lijst voor het schrijven van de script zelf. Uiteindelijk de array moet geimporteerd worden van echte DB--!----BELANGRIJK-----
?>